import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Chargement de la police Inter avec le sous-ensemble latin
const inter = Inter({ subsets: ["latin"] });

// Définition des métadonnées globales pour l'application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> {/* Définition de la langue du document */}
      <body className={inter.className}> {/* Application de la police à tout le document */}
        {children} {/* Inclusion du contenu des pages */}
      </body>
    </html>
  );
}
